---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: <name>
          image: <DockerHub-user>/<repository-name>:<image tag-game>
          imagePullPolicy: Always
          ports:
            - name: port
              containerPort: 80
              protocol: TCP
