---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: homework
spec:
  type: NodePort
  ports:
    - nodePort: 31234
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
